version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - /home/wp-nginx-php-fpm/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  nginx:
    image: nginx:latest
    volumes:
      - /home/wp-nginx-php-fpm/data/nginx/conf.d:/etc/nginx/conf.d
      - /home/wp-nginx-php-fpm/data/site:/var/www/henrydev.pp.ua
      - /home/wp-nginx-php-fpm/data/certbot:/etc/letsencrypt
      - /home/wp-nginx-php-fpm/data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile-php-fpm
    ports:
      - "9000:9000"
    volumes:
      - /home/wp-nginx-php-fpm/data/site:/var/www/henrydev.pp.ua

  certbot:
    image: certbot/certbot
    volumes: 
      - /home/wp-nginx-php-fpm/data/certbot:/etc/letsencrypt
      - /home/wp-nginx-php-fpm/data/certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --email test@test.test -d henrydev.pp.ua -d www.henrydev.pp.ua --agree-tos  

