version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - /home/ubuntu/data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
  
  nginx:
    image: nginx:latest
    volumes:
      - /home/ubuntu/data/nginx/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/data/site:/var/www/henrydev.pp.ua
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    image: php:7.4-fpm
    volumes:
      - /home/ubuntu/data/php-fpm:/usr/local/etc/php-fpm.d
      - /home/ubuntu/data/site:/var/www/henrydev.pp.ua
    ports:
      - "127.0.0.1:9000:9000"
