name: wordpress-install

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Make home dir and copy data
        run: |
          sudo mkdir /home/wp-nginx-php-fpm
          cp * /home/wp-nginx-php-fpm/
          ls -la /home/wp-nginx-php-fpm
