name: wordpress-install

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_HOME_DIR: /home/wp-nginx-php-fpm
  SITE_HOME_DIR: /home/wp-nginx-php-fpm/data/site

jobs:
  setup:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3

      - name: Make project home dir and copy data
        run: |
          sudo mkdir ${{ env.PROJECT_HOME_DIR }}
          sudo cp -R * ${{ env.PROJECT_HOME_DIR }}
          sudo ls -la ${{ env.PROJECT_HOME_DIR }}
          
      - name: Make site home dir and download Wordpress
        run: |
          sudo mkdir ${{ env.SITE_HOME_DIR }}
          cd ${{ env.SITE_HOME_DIR }}
          sudo curl -O https://wordpress.org/latest.zip
          sudo unzip latest.zip
          sudo mv wordpress/* .
          sudo rm -rf wordpress latest.zip
          sudo chown -R www-data: ${{ env.SITE_HOME_DIR }}

      - name: Install Docker and Docker-compose
        run: |
          sudo apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
          sudo mkdir -p /etc/apt/keyrings
          sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg > docker.txt
          sudo gpg --dearmor < docker.txt > docker.gpg
          sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
          sudo apt update
          sudo apt install -y docker-ce docker-ce-cli containerd.io docker-compose
          sudo systemctl restart docker
                    
  docker-compose:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Run docker compose
        run: |
          cd ${{ env.PROJECT_HOME_DIR }} 
          sudo docker-compose up -d 

