name: wordpress-install

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_HOME_DIR: /home/wp-nginx-php-fpm
  SITE_HOME_DIR: /home/wp-nginx-php-fpm/data/site

jobs:
  setup:
    runs-on: self-hosted
    steps: 
      - uses: actions/checkout@v3

      - name: Make project home dir and copy data
        run: |
          sudo mkdir ${{ env.PROJECT_HOME_DIR }}
          sudo cp -R * ${{ env.PROJECT_HOME_DIR }}
          sudo ls -la ${{ env.PROJECT_HOME_DIR }}
          
      - name: Make site home dir and download Wordpress
        run: |
          sudo mkdir ${{ env.SITE_HOME_DIR }}
          cd ${{ env.SITE_HOME_DIR }}
          sudo curl -O https://wordpress.org/latest.zip
          sudo unzip latest.zip
          sudo mv wordpress/* .
          sudo rm -rf wordpress latest.zip
          sudo chown -R www-data: ${{ env.SITE_HOME_DIR }}

      - name: Install Docker and Docker-compose
        run: |
          sudo apt update -y
          sudo apt apgrade -y
          sudo mkdir -p /home/.docker/cli-plugins
          sudo curl -SL https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64 -o /home/.docker/cli-plugins/docker-compose
          sudo chmod +x /home/.docker/cli-plugins/docker-compose
                    
  docker-compose:
    runs-on: self-hosted
    needs: setup
    steps:
      - name: Run docker compose
        run: |
          cd ${{ env.PROJECT_HOME_DIR }}
          sudo docker-compose up -d
